export interface Pais {
  nome: string;
  codigo: string;
  estados: Estado[];
}

export interface Estado {
  nome: string;
  sigla: string;
  cidades: string[];
}

export const paises: Pais[] = [
  {
    nome: "Brasil",
    codigo: "BR",
    estados: [
      { nome: "Acre", sigla: "AC", cidades: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá", "Feijó", "Brasiléia"] },
      { nome: "Alagoas", sigla: "AL", cidades: ["Maceió", "Arapiraca", "Rio Largo", "Palmeira dos Índios", "Penedo", "União dos Palmares", "São Miguel dos Campos"] },
      { nome: "Amapá", sigla: "AP", cidades: ["Macapá", "Santana", "Laranjal do Jari", "Oiapoque", "Mazagão"] },
      { nome: "Amazonas", sigla: "AM", cidades: ["Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari", "Tefé", "Tabatinga", "Maués"] },
      { nome: "Bahia", sigla: "BA", cidades: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna", "Juazeiro", "Lauro de Freitas", "Ilhéus", "Jequié", "Teixeira de Freitas", "Alagoinhas", "Barreiras", "Porto Seguro", "Simões Filho", "Paulo Afonso", "Eunápolis", "Santo Antônio de Jesus", "Valença", "Candeias", "Guanambi"] },
      { nome: "Ceará", sigla: "CE", cidades: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral", "Crato", "Itapipoca", "Maranguape", "Iguatu", "Quixadá", "Canindé", "Pacatuba", "Aquiraz"] },
      { nome: "Distrito Federal", sigla: "DF", cidades: ["Brasília", "Ceilândia", "Taguatinga", "Samambaia", "Plano Piloto", "Águas Claras", "Recanto das Emas", "Gama"] },
      { nome: "Espírito Santo", sigla: "ES", cidades: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Cachoeiro de Itapemirim", "Linhares", "São Mateus", "Colatina", "Guarapari", "Aracruz"] },
      { nome: "Goiás", sigla: "GO", cidades: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde", "Luziânia", "Águas Lindas de Goiás", "Valparaíso de Goiás", "Trindade", "Formosa", "Novo Gama", "Itumbiara", "Senador Canedo", "Catalão", "Jataí"] },
      { nome: "Maranhão", sigla: "MA", cidades: ["São Luís", "Imperatriz", "Timon", "Caxias", "Codó", "Paço do Lumiar", "Açailândia", "Bacabal", "Santa Inês", "Balsas"] },
      { nome: "Mato Grosso", sigla: "MT", cidades: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop", "Tangará da Serra", "Cáceres", "Sorriso", "Lucas do Rio Verde", "Primavera do Leste", "Barra do Garças"] },
      { nome: "Mato Grosso do Sul", sigla: "MS", cidades: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá", "Ponta Porã", "Naviraí", "Nova Andradina", "Aquidauana", "Sidrolândia", "Maracaju"] },
      { nome: "Minas Gerais", sigla: "MG", cidades: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba", "Governador Valadares", "Ipatinga", "Sete Lagoas", "Divinópolis", "Santa Luzia", "Ibirité", "Poços de Caldas", "Patos de Minas", "Teófilo Otoni", "Barbacena", "Sabará", "Varginha", "Conselheiro Lafaiete", "Muriaé", "Araguari", "Itabira", "Passos", "Pouso Alegre", "Lavras", "Nova Lima", "Itajubá", "Coronel Fabriciano"] },
      { nome: "Pará", sigla: "PA", cidades: ["Belém", "Ananindeua", "Santarém", "Marabá", "Parauapebas", "Castanhal", "Abaetetuba", "Cametá", "Marituba", "Bragança", "Altamira", "Tucuruí", "Itaituba", "Barcarena"] },
      { nome: "Paraíba", sigla: "PB", cidades: ["João Pessoa", "Campina Grande", "Santa Rita", "Patos", "Bayeux", "Sousa", "Cajazeiras", "Cabedelo", "Guarabira", "Sapé"] },
      { nome: "Paraná", sigla: "PR", cidades: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "São José dos Pinhais", "Foz do Iguaçu", "Colombo", "Guarapuava", "Paranaguá", "Araucária", "Toledo", "Apucarana", "Pinhais", "Campo Largo", "Arapongas", "Almirante Tamandaré", "Umuarama", "Piraquara", "Cambé"] },
      { nome: "Pernambuco", sigla: "PE", cidades: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina", "Paulista", "Cabo de Santo Agostinho", "Camaragibe", "Garanhuns", "Vitória de Santo Antão", "Igarassu", "São Lourenço da Mata", "Abreu e Lima", "Serra Talhada"] },
      { nome: "Piauí", sigla: "PI", cidades: ["Teresina", "Parnaíba", "Picos", "Piripiri", "Floriano", "Campo Maior", "Barras", "Pedro II", "Oeiras"] },
      { nome: "Rio de Janeiro", sigla: "RJ", cidades: ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói", "Belford Roxo", "Campos dos Goytacazes", "Petrópolis", "Volta Redonda", "São João de Meriti", "Magé", "Itaboraí", "Macaé", "Mesquita", "Nilópolis", "Teresópolis", "Queimados", "Nova Friburgo", "Maricá", "Cabo Frio", "Angra dos Reis", "Barra Mansa", "Resende", "Araruama"] },
      { nome: "Rio Grande do Norte", sigla: "RN", cidades: ["Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante", "Macaíba", "Ceará-Mirim", "Caicó", "Açu", "Currais Novos", "São José de Mipibu"] },
      { nome: "Rio Grande do Sul", sigla: "RS", cidades: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí", "Viamão", "Novo Hamburgo", "São Leopoldo", "Rio Grande", "Alvorada", "Passo Fundo", "Sapucaia do Sul", "Uruguaiana", "Santa Cruz do Sul", "Cachoeirinha", "Bagé", "Bento Gonçalves", "Erechim", "Guaíba", "Lajeado", "Ijuí", "Sapiranga", "Campo Bom", "Estância Velha", "Ivoti", "Dois Irmãos", "Parobé", "Taquara", "Montenegro", "Farroupilha", "Vacaria", "Venâncio Aires", "Camaquã", "São Gabriel", "Alegrete", "Santana do Livramento", "Rosário do Sul", "Cruz Alta", "Santiago", "Santo Ângelo", "São Borja", "Carazinho", "Marau", "Não-Me-Toque", "Estrela", "Teutônia", "Encantado", "Arroio do Meio", "Carlos Barbosa", "Garibaldi", "Flores da Cunha", "Veranópolis", "Nova Petrópolis", "Gramado", "Canela", "São Marcos", "Charqueadas", "São Jerônimo", "Triunfo", "Eldorado do Sul", "Igrejinha", "Três Coroas", "Rolante", "Riozinho", "Feliz", "Capela de Santana", "São Sebastião do Caí", "Portão", "Nova Santa Rita", "Cachoeira do Sul", "Osório", "Tramandaí", "Capão da Canoa", "Torres", "Cidreira", "Imbé", "Xangri-lá", "Santo Antônio da Patrulha", "Tapes", "São Lourenço do Sul", "Jaguarão", "Canguçu", "Piratini", "Pedro Osório", "Capão do Leão", "Arroio Grande", "Santa Vitória do Palmar", "Chuí"] },
      { nome: "Rondônia", sigla: "RO", cidades: ["Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena", "Cacoal", "Rolim de Moura", "Jaru", "Guajará-Mirim"] },
      { nome: "Roraima", sigla: "RR", cidades: ["Boa Vista", "Rorainópolis", "Caracaraí", "Pacaraima", "Alto Alegre"] },
      { nome: "Santa Catarina", sigla: "SC", cidades: ["Florianópolis", "Joinville", "Blumenau", "São José", "Chapecó", "Criciúma", "Itajaí", "Jaraguá do Sul", "Palhoça", "Lages", "Balneário Camboriú", "Brusque", "Tubarão", "São Bento do Sul", "Caçador", "Concórdia", "Navegantes", "Rio do Sul", "Camboriú", "Gaspar"] },
      { nome: "São Paulo", sigla: "SP", cidades: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "São José dos Campos", "Sorocaba", "Ribeirão Preto", "Santos", "Mauá", "São José do Rio Preto", "Piracicaba", "Mogi das Cruzes", "Diadema", "Jundiaí", "Carapicuíba", "Bauru", "São Vicente", "Itaquaquecetuba", "Franca", "Praia Grande", "Guarujá", "Taubaté", "Limeira", "Suzano", "Taboão da Serra", "Sumaré", "Barueri", "Embu das Artes", "Indaiatuba", "Cotia", "Marília", "Americana", "Araraquara", "Jacareí", "Presidente Prudente", "São Carlos", "Itapevi", "Hortolândia", "Rio Claro"] },
      { nome: "Sergipe", sigla: "SE", cidades: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto", "Itabaiana", "Estância", "São Cristóvão", "Tobias Barreto"] },
      { nome: "Tocantins", sigla: "TO", cidades: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional", "Paraíso do Tocantins", "Colinas do Tocantins"] },
    ],
  },
  {
    nome: "Portugal",
    codigo: "PT",
    estados: [
      { nome: "Lisboa", sigla: "LI", cidades: ["Lisboa", "Sintra", "Cascais", "Loures", "Almada", "Amadora", "Oeiras", "Seixal", "Odivelas", "Vila Franca de Xira", "Mafra", "Barreiro", "Moita", "Setúbal"] },
      { nome: "Porto", sigla: "PO", cidades: ["Porto", "Vila Nova de Gaia", "Matosinhos", "Maia", "Gondomar", "Valongo", "Paredes", "Penafiel", "Santa Maria da Feira", "Espinho"] },
      { nome: "Braga", sigla: "BR", cidades: ["Braga", "Guimarães", "Barcelos", "Famalicão", "Fafe", "Vizela", "Amares", "Cabeceiras de Basto"] },
      { nome: "Aveiro", sigla: "AV", cidades: ["Aveiro", "Águeda", "Ovar", "Ílhavo", "São João da Madeira", "Oliveira de Azeméis", "Estarreja"] },
      { nome: "Faro", sigla: "FA", cidades: ["Faro", "Portimão", "Loulé", "Albufeira", "Lagos", "Olhão", "Tavira", "Silves", "Vila Real de Santo António", "Lagoa"] },
      { nome: "Coimbra", sigla: "CO", cidades: ["Coimbra", "Figueira da Foz", "Cantanhede", "Montemor-o-Velho", "Condeixa-a-Nova"] },
      { nome: "Leiria", sigla: "LE", cidades: ["Leiria", "Caldas da Rainha", "Marinha Grande", "Pombal", "Peniche", "Alcobaça"] },
      { nome: "Viseu", sigla: "VI", cidades: ["Viseu", "Lamego", "Tondela", "Mangualde", "São Pedro do Sul"] },
      { nome: "Viana do Castelo", sigla: "VC", cidades: ["Viana do Castelo", "Ponte de Lima", "Valença", "Caminha", "Monção"] },
      { nome: "Santarém", sigla: "SA", cidades: ["Santarém", "Tomar", "Abrantes", "Torres Novas", "Ourém", "Entroncamento"] },
      { nome: "Évora", sigla: "EV", cidades: ["Évora", "Estremoz", "Montemor-o-Novo", "Vendas Novas", "Reguengos de Monsaraz"] },
      { nome: "Madeira", sigla: "MA", cidades: ["Funchal", "Câmara de Lobos", "Santa Cruz", "Machico", "Ribeira Brava"] },
      { nome: "Açores", sigla: "AC", cidades: ["Ponta Delgada", "Angra do Heroísmo", "Horta", "Ribeira Grande", "Praia da Vitória"] },
    ],
  },
  {
    nome: "Estados Unidos",
    codigo: "US",
    estados: [
      { nome: "Alabama", sigla: "AL", cidades: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"] },
      { nome: "Arizona", sigla: "AZ", cidades: ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler", "Tempe"] },
      { nome: "Califórnia", sigla: "CA", cidades: ["Los Angeles", "San Francisco", "San Diego", "Sacramento", "San Jose", "Fresno", "Long Beach", "Oakland", "Santa Ana", "Anaheim", "Riverside", "Bakersfield", "Irvine"] },
      { nome: "Colorado", sigla: "CO", cidades: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder", "Lakewood"] },
      { nome: "Connecticut", sigla: "CT", cidades: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"] },
      { nome: "Flórida", sigla: "FL", cidades: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale", "St. Petersburg", "Hialeah", "Tallahassee", "Cape Coral", "Port St. Lucie", "Pompano Beach"] },
      { nome: "Geórgia", sigla: "GA", cidades: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Macon"] },
      { nome: "Illinois", sigla: "IL", cidades: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield", "Elgin", "Peoria"] },
      { nome: "Massachusetts", sigla: "MA", cidades: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "New Bedford", "Fall River"] },
      { nome: "Michigan", sigla: "MI", cidades: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing", "Flint"] },
      { nome: "Nova Jersey", sigla: "NJ", cidades: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Trenton", "Clifton"] },
      { nome: "Nova York", sigla: "NY", cidades: ["New York City", "Buffalo", "Rochester", "Albany", "Syracuse", "Yonkers", "New Rochelle"] },
      { nome: "Ohio", sigla: "OH", cidades: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"] },
      { nome: "Pensilvânia", sigla: "PA", cidades: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton"] },
      { nome: "Texas", sigla: "TX", cidades: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo", "Lubbock"] },
      { nome: "Washington", sigla: "WA", cidades: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent"] },
    ],
  },
  {
    nome: "Angola",
    codigo: "AO",
    estados: [
      { nome: "Bengo", sigla: "BGO", cidades: ["Caxito", "Ambriz", "Nambuangongo"] },
      { nome: "Benguela", sigla: "BEN", cidades: ["Benguela", "Lobito", "Catumbela", "Cubal", "Ganda", "Baía Farta"] },
      { nome: "Bié", sigla: "BIE", cidades: ["Kuito", "Camacupa", "Chinguar", "Andulo"] },
      { nome: "Cabinda", sigla: "CAB", cidades: ["Cabinda", "Buco-Zau", "Cacongo"] },
      { nome: "Cunene", sigla: "CNN", cidades: ["Ondjiva", "Xangongo", "Cuanhama"] },
      { nome: "Huambo", sigla: "HUA", cidades: ["Huambo", "Caála", "Longonjo", "Bailundo", "Mungo", "Ucuma"] },
      { nome: "Huíla", sigla: "HUI", cidades: ["Lubango", "Matala", "Chibia", "Caluquembe", "Caconda", "Humpata"] },
      { nome: "Kwanza Norte", sigla: "KNO", cidades: ["N'dalatando", "Cambambe", "Cazengo", "Lucala"] },
      { nome: "Kwanza Sul", sigla: "KSU", cidades: ["Sumbe", "Porto Amboim", "Gabela", "Waku Kungo"] },
      { nome: "Luanda", sigla: "LUA", cidades: ["Luanda", "Viana", "Cacuaco", "Belas", "Cazenga", "Kilamba Kiaxi", "Talatona"] },
      { nome: "Lunda Norte", sigla: "LNO", cidades: ["Dundo", "Lucapa", "Chitato"] },
      { nome: "Lunda Sul", sigla: "LSU", cidades: ["Saurimo", "Muconda", "Cacolo"] },
      { nome: "Malanje", sigla: "MAL", cidades: ["Malanje", "Cacuso", "Calandula"] },
      { nome: "Moxico", sigla: "MOX", cidades: ["Luena", "Moxico", "Bundas", "Léua"] },
      { nome: "Namibe", sigla: "NAM", cidades: ["Moçâmedes", "Tômbua", "Bibala", "Virei"] },
      { nome: "Uíge", sigla: "UIG", cidades: ["Uíge", "Negage", "Maquela do Zombo"] },
      { nome: "Zaire", sigla: "ZAI", cidades: ["M'banza-Kongo", "Soyo", "Cuimba", "Nóqui"] },
    ],
  },
  {
    nome: "Moçambique",
    codigo: "MZ",
    estados: [
      { nome: "Maputo Cidade", sigla: "MPC", cidades: ["Maputo"] },
      { nome: "Maputo Província", sigla: "MPM", cidades: ["Matola", "Boane", "Marracuene", "Manhiça", "Namaacha"] },
      { nome: "Gaza", sigla: "GAZ", cidades: ["Xai-Xai", "Chókwè", "Chibuto", "Bilene", "Mandlakazi"] },
      { nome: "Inhambane", sigla: "INH", cidades: ["Inhambane", "Maxixe", "Vilankulo", "Massinga", "Homoíne"] },
      { nome: "Sofala", sigla: "SOF", cidades: ["Beira", "Dondo", "Gorongosa", "Marromeu", "Búzi"] },
      { nome: "Manica", sigla: "MAN", cidades: ["Chimoio", "Gondola", "Manica", "Catandica", "Sussundenga"] },
      { nome: "Tete", sigla: "TET", cidades: ["Tete", "Moatize", "Cahora Bassa", "Changara", "Angónia"] },
      { nome: "Zambézia", sigla: "ZAM", cidades: ["Quelimane", "Mocuba", "Guruè", "Milange", "Alto Molócuè"] },
      { nome: "Nampula", sigla: "NAM", cidades: ["Nampula", "Nacala", "Ilha de Moçambique", "Angoche", "Monapo", "Meconta"] },
      { nome: "Niassa", sigla: "NIA", cidades: ["Lichinga", "Cuamba", "Mandimba", "Marrupa"] },
      { nome: "Cabo Delgado", sigla: "CDG", cidades: ["Pemba", "Montepuez", "Mocímboa da Praia", "Chiúre", "Mueda"] },
    ],
  },
  {
    nome: "Cabo Verde",
    codigo: "CV",
    estados: [
      { nome: "Santiago", sigla: "S", cidades: ["Praia", "Assomada", "Tarrafal", "Pedra Badejo", "Calheta de São Miguel", "Cidade Velha"] },
      { nome: "São Vicente", sigla: "SV", cidades: ["Mindelo"] },
      { nome: "Santo Antão", sigla: "SA", cidades: ["Porto Novo", "Ribeira Grande", "Paul", "Ponta do Sol"] },
      { nome: "Sal", sigla: "SL", cidades: ["Espargos", "Santa Maria"] },
      { nome: "Boa Vista", sigla: "BV", cidades: ["Sal Rei", "Rabil"] },
      { nome: "Fogo", sigla: "FO", cidades: ["São Filipe", "Mosteiros", "Cova Figueira"] },
      { nome: "São Nicolau", sigla: "SN", cidades: ["Ribeira Brava", "Tarrafal de São Nicolau"] },
      { nome: "Maio", sigla: "MA", cidades: ["Vila do Maio", "Calheta"] },
      { nome: "Brava", sigla: "BR", cidades: ["Nova Sintra", "Vila Nova Sintra"] },
    ],
  },
  {
    nome: "Guiné-Bissau",
    codigo: "GW",
    estados: [
      { nome: "Bissau", sigla: "BS", cidades: ["Bissau"] },
      { nome: "Bafatá", sigla: "BA", cidades: ["Bafatá", "Bambadinca", "Contuboel"] },
      { nome: "Gabú", sigla: "GA", cidades: ["Gabú", "Pitche", "Sonaco"] },
      { nome: "Cacheu", sigla: "CA", cidades: ["Cacheu", "Canchungo", "São Domingos"] },
      { nome: "Biombo", sigla: "BM", cidades: ["Quinhámel", "Bissorã"] },
      { nome: "Oio", sigla: "OI", cidades: ["Farim", "Mansôa", "Nhacra"] },
    ],
  },
  {
    nome: "São Tomé e Príncipe",
    codigo: "ST",
    estados: [
      { nome: "São Tomé", sigla: "ST", cidades: ["São Tomé", "Trindade", "Neves", "Santana", "Guadalupe"] },
      { nome: "Príncipe", sigla: "PR", cidades: ["Santo António"] },
    ],
  },
  {
    nome: "Timor-Leste",
    codigo: "TL",
    estados: [
      { nome: "Díli", sigla: "DI", cidades: ["Díli", "Metinaro", "Ataúro"] },
      { nome: "Baucau", sigla: "BA", cidades: ["Baucau", "Venilale", "Quelicai"] },
      { nome: "Ermera", sigla: "ER", cidades: ["Gleno", "Atsabe", "Hatolia"] },
    ],
  },
  {
    nome: "Itália",
    codigo: "IT",
    estados: [
      { nome: "Lazio", sigla: "LAZ", cidades: ["Roma", "Latina", "Frosinone", "Viterbo", "Rieti", "Guidonia", "Fiumicino", "Tivoli"] },
      { nome: "Lombardia", sigla: "LOM", cidades: ["Milão", "Brescia", "Bergamo", "Monza", "Como", "Varese", "Cremona", "Pavia", "Mantova"] },
      { nome: "Campânia", sigla: "CAM", cidades: ["Nápoles", "Salerno", "Caserta", "Avellino", "Benevento", "Torre del Greco", "Giugliano"] },
      { nome: "Toscana", sigla: "TOS", cidades: ["Florença", "Pisa", "Livorno", "Siena", "Arezzo", "Prato", "Lucca", "Grosseto", "Pistoia"] },
      { nome: "Piemonte", sigla: "PIE", cidades: ["Turim", "Novara", "Alessandria", "Asti", "Cuneo", "Vercelli"] },
      { nome: "Vêneto", sigla: "VEN", cidades: ["Veneza", "Verona", "Pádua", "Vicenza", "Treviso", "Rovigo"] },
      { nome: "Sicília", sigla: "SIC", cidades: ["Palermo", "Catânia", "Messina", "Siracusa", "Ragusa", "Agrigento", "Trapani"] },
      { nome: "Emília-Romanha", sigla: "EMR", cidades: ["Bolonha", "Parma", "Módena", "Reggio Emilia", "Ravena", "Ferrara", "Rimini"] },
      { nome: "Sardenha", sigla: "SAR", cidades: ["Cagliari", "Sassari", "Quartu Sant'Elena", "Olbia", "Alghero", "Nuoro"] },
    ],
  },
  {
    nome: "Espanha",
    codigo: "ES",
    estados: [
      { nome: "Madrid", sigla: "MAD", cidades: ["Madrid", "Alcalá de Henares", "Móstoles", "Fuenlabrada", "Leganés", "Getafe", "Alcorcón", "Torrejón de Ardoz"] },
      { nome: "Catalunha", sigla: "CAT", cidades: ["Barcelona", "Tarragona", "Lleida", "Girona", "L'Hospitalet de Llobregat", "Badalona", "Terrassa", "Sabadell", "Mataró"] },
      { nome: "Andaluzia", sigla: "AND", cidades: ["Sevilha", "Málaga", "Granada", "Córdoba", "Cádiz", "Almería", "Huelva", "Jaén", "Jerez de la Frontera", "Marbella"] },
      { nome: "Valência", sigla: "VAL", cidades: ["Valência", "Alicante", "Elche", "Castellón", "Torrevieja", "Benidorm", "Gandía"] },
      { nome: "País Basco", sigla: "PV", cidades: ["Bilbao", "Vitória-Gasteiz", "San Sebastián", "Barakaldo", "Getxo", "Irún"] },
      { nome: "Galiza", sigla: "GA", cidades: ["Vigo", "A Coruña", "Santiago de Compostela", "Ourense", "Lugo", "Pontevedra", "Ferrol"] },
      { nome: "Ilhas Canárias", sigla: "CN", cidades: ["Las Palmas", "Santa Cruz de Tenerife", "La Laguna", "Arrecife", "Puerto del Rosario"] },
    ],
  },
  {
    nome: "França",
    codigo: "FR",
    estados: [
      { nome: "Île-de-France", sigla: "IDF", cidades: ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Montreuil", "Nanterre", "Vitry-sur-Seine", "Créteil", "Versalhes"] },
      { nome: "Provence-Alpes-Côte d'Azur", sigla: "PAC", cidades: ["Marselha", "Nice", "Toulon", "Aix-en-Provence", "Avignon", "Cannes", "Antibes"] },
      { nome: "Auvergne-Rhône-Alpes", sigla: "ARA", cidades: ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand", "Villeurbanne", "Annecy", "Valence"] },
      { nome: "Occitânia", sigla: "OCC", cidades: ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers", "Narbonne"] },
      { nome: "Nova Aquitânia", sigla: "NAQ", cidades: ["Bordeaux", "Limoges", "Poitiers", "Pau", "La Rochelle", "Bayonne", "Angoulême"] },
      { nome: "Bretanha", sigla: "BRE", cidades: ["Rennes", "Brest", "Quimper", "Lorient", "Vannes", "Saint-Brieuc", "Saint-Malo"] },
      { nome: "Hauts-de-France", sigla: "HDF", cidades: ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkerque", "Calais"] },
      { nome: "Grand Est", sigla: "GES", cidades: ["Estrasburgo", "Reims", "Metz", "Mulhouse", "Nancy", "Colmar"] },
    ],
  },
  {
    nome: "Reino Unido",
    codigo: "GB",
    estados: [
      { nome: "Inglaterra", sigla: "ENG", cidades: ["Londres", "Manchester", "Birmingham", "Liverpool", "Leeds", "Sheffield", "Bristol", "Leicester", "Nottingham", "Newcastle", "Coventry", "Bradford", "Southampton", "Plymouth", "Oxford", "Cambridge", "Reading", "Brighton", "Milton Keynes"] },
      { nome: "Escócia", sigla: "SCT", cidades: ["Edimburgo", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling", "Perth"] },
      { nome: "País de Gales", sigla: "WLS", cidades: ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry", "Bangor"] },
      { nome: "Irlanda do Norte", sigla: "NIR", cidades: ["Belfast", "Derry", "Lisburn", "Newry", "Bangor"] },
    ],
  },
  {
    nome: "Alemanha",
    codigo: "DE",
    estados: [
      { nome: "Baviera", sigla: "BY", cidades: ["Munique", "Nuremberg", "Augsburg", "Regensburg", "Würzburg", "Ingolstadt", "Fürth"] },
      { nome: "Berlim", sigla: "BE", cidades: ["Berlim"] },
      { nome: "Hamburgo", sigla: "HH", cidades: ["Hamburgo"] },
      { nome: "Hesse", sigla: "HE", cidades: ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"] },
      { nome: "Renânia do Norte-Vestfália", sigla: "NW", cidades: ["Colônia", "Düsseldorf", "Dortmund", "Essen", "Duisburg", "Bochum", "Wuppertal", "Bonn", "Münster", "Bielefeld", "Aachen"] },
      { nome: "Baden-Württemberg", sigla: "BW", cidades: ["Stuttgart", "Mannheim", "Karlsruhe", "Freiburg", "Heidelberg", "Ulm", "Heilbronn"] },
      { nome: "Baixa Saxônia", sigla: "NI", cidades: ["Hanôver", "Braunschweig", "Osnabrück", "Wolfsburg", "Göttingen", "Oldenburg"] },
      { nome: "Saxônia", sigla: "SN", cidades: ["Dresden", "Leipzig", "Chemnitz", "Zwickau"] },
    ],
  },
  {
    nome: "Argentina",
    codigo: "AR",
    estados: [
      { nome: "Buenos Aires", sigla: "BA", cidades: ["Buenos Aires", "La Plata", "Mar del Plata", "Bahía Blanca", "Tandil", "Quilmes", "Lanús", "Lomas de Zamora", "Morón"] },
      { nome: "Córdoba", sigla: "CO", cidades: ["Córdoba", "Villa María", "Río Cuarto", "San Francisco", "Villa Carlos Paz"] },
      { nome: "Santa Fe", sigla: "SF", cidades: ["Rosário", "Santa Fe", "Rafaela", "Venado Tuerto", "Reconquista"] },
      { nome: "Mendoza", sigla: "MZ", cidades: ["Mendoza", "San Rafael", "Godoy Cruz", "Luján de Cuyo", "Maipú"] },
      { nome: "Tucumán", sigla: "TU", cidades: ["San Miguel de Tucumán", "Yerba Buena", "Tafí Viejo", "Concepción"] },
      { nome: "Salta", sigla: "SA", cidades: ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "Metán"] },
      { nome: "Misiones", sigla: "MI", cidades: ["Posadas", "Oberá", "Eldorado", "Puerto Iguazú"] },
    ],
  },
  {
    nome: "Colômbia",
    codigo: "CO",
    estados: [
      { nome: "Bogotá", sigla: "DC", cidades: ["Bogotá"] },
      { nome: "Antioquia", sigla: "ANT", cidades: ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Rionegro", "Turbo"] },
      { nome: "Valle del Cauca", sigla: "VAL", cidades: ["Cali", "Buenaventura", "Palmira", "Tuluá", "Yumbo", "Cartago"] },
      { nome: "Atlántico", sigla: "ATL", cidades: ["Barranquilla", "Soledad", "Malambo", "Sabanalarga"] },
      { nome: "Santander", sigla: "SAN", cidades: ["Bucaramanga", "Floridablanca", "Girón", "Piedecuesta", "Barrancabermeja"] },
      { nome: "Bolívar", sigla: "BOL", cidades: ["Cartagena", "Magangué", "Turbaco", "Arjona", "El Carmen de Bolívar"] },
    ],
  },
  {
    nome: "México",
    codigo: "MX",
    estados: [
      { nome: "Ciudad de México", sigla: "CDMX", cidades: ["Ciudad de México"] },
      { nome: "Estado de México", sigla: "MEX", cidades: ["Ecatepec", "Nezahualcóyotl", "Toluca", "Naucalpan", "Tlalnepantla", "Chimalhuacán"] },
      { nome: "Jalisco", sigla: "JAL", cidades: ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta", "Lagos de Moreno"] },
      { nome: "Nuevo León", sigla: "NL", cidades: ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "Santa Catarina"] },
      { nome: "Puebla", sigla: "PUE", cidades: ["Puebla", "Tehuacán", "San Martín Texmelucan", "Atlixco", "Cholula"] },
      { nome: "Veracruz", sigla: "VER", cidades: ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Poza Rica", "Boca del Río"] },
      { nome: "Guanajuato", sigla: "GTO", cidades: ["León", "Irapuato", "Celaya", "Guanajuato", "Salamanca", "San Miguel de Allende"] },
    ],
  },
  {
    nome: "Japão",
    codigo: "JP",
    estados: [
      { nome: "Tóquio", sigla: "TK", cidades: ["Tóquio", "Shinjuku", "Shibuya", "Hachioji", "Machida"] },
      { nome: "Osaka", sigla: "OS", cidades: ["Osaka", "Sakai", "Higashiosaka", "Toyonaka", "Suita"] },
      { nome: "Kanagawa", sigla: "KN", cidades: ["Yokohama", "Kawasaki", "Sagamihara", "Fujisawa", "Kamakura"] },
      { nome: "Aichi", sigla: "AI", cidades: ["Nagoia", "Toyota", "Okazaki", "Ichinomiya", "Kasugai"] },
      { nome: "Hokkaido", sigla: "HK", cidades: ["Sapporo", "Asahikawa", "Hakodate", "Kushiro", "Obihiro"] },
      { nome: "Fukuoka", sigla: "FK", cidades: ["Fukuoka", "Kitakyushu", "Kurume", "Omuta"] },
    ],
  },
  {
    nome: "Canadá",
    codigo: "CA",
    estados: [
      { nome: "Ontário", sigla: "ON", cidades: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener"] },
      { nome: "Quebec", sigla: "QC", cidades: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke"] },
      { nome: "Colúmbia Britânica", sigla: "BC", cidades: ["Vancouver", "Surrey", "Burnaby", "Richmond", "Victoria", "Kelowna"] },
      { nome: "Alberta", sigla: "AB", cidades: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat"] },
      { nome: "Manitoba", sigla: "MB", cidades: ["Winnipeg", "Brandon", "Steinbach", "Thompson"] },
    ],
  },
  {
    nome: "Austrália",
    codigo: "AU",
    estados: [
      { nome: "Nova Gales do Sul", sigla: "NSW", cidades: ["Sydney", "Newcastle", "Wollongong", "Central Coast", "Maitland"] },
      { nome: "Vitória", sigla: "VIC", cidades: ["Melbourne", "Geelong", "Ballarat", "Bendigo"] },
      { nome: "Queensland", sigla: "QLD", cidades: ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns"] },
      { nome: "Austrália Ocidental", sigla: "WA", cidades: ["Perth", "Mandurah", "Bunbury", "Geraldton"] },
      { nome: "Austrália Meridional", sigla: "SA", cidades: ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge"] },
    ],
  },
  {
    nome: "Índia",
    codigo: "IN",
    estados: [
      { nome: "Maharashtra", sigla: "MH", cidades: ["Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Aurangabad"] },
      { nome: "Delhi", sigla: "DL", cidades: ["Nova Delhi", "Delhi"] },
      { nome: "Karnataka", sigla: "KA", cidades: ["Bangalore", "Mysore", "Hubli-Dharwad", "Mangalore"] },
      { nome: "Tamil Nadu", sigla: "TN", cidades: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"] },
      { nome: "Uttar Pradesh", sigla: "UP", cidades: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Allahabad", "Noida", "Ghaziabad"] },
    ],
  },
  {
    nome: "China",
    codigo: "CN",
    estados: [
      { nome: "Pequim", sigla: "BJ", cidades: ["Pequim"] },
      { nome: "Xangai", sigla: "SH", cidades: ["Xangai"] },
      { nome: "Guangdong", sigla: "GD", cidades: ["Guangzhou", "Shenzhen", "Dongguan", "Foshan", "Zhuhai"] },
      { nome: "Zhejiang", sigla: "ZJ", cidades: ["Hangzhou", "Ningbo", "Wenzhou", "Shaoxing"] },
      { nome: "Sichuan", sigla: "SC", cidades: ["Chengdu", "Mianyang", "Deyang", "Leshan"] },
    ],
  },
  {
    nome: "Coreia do Sul",
    codigo: "KR",
    estados: [
      { nome: "Seul", sigla: "SEO", cidades: ["Seul"] },
      { nome: "Busan", sigla: "BUS", cidades: ["Busan"] },
      { nome: "Gyeonggi", sigla: "GYG", cidades: ["Suwon", "Seongnam", "Goyang", "Yongin", "Bucheon", "Ansan", "Anyang"] },
      { nome: "Incheon", sigla: "INC", cidades: ["Incheon"] },
    ],
  },
  {
    nome: "Nigéria",
    codigo: "NG",
    estados: [
      { nome: "Lagos", sigla: "LA", cidades: ["Lagos", "Ikeja", "Lekki", "Victoria Island", "Surulere"] },
      { nome: "Abuja", sigla: "FC", cidades: ["Abuja", "Gwagwalada", "Kuje"] },
      { nome: "Rivers", sigla: "RI", cidades: ["Port Harcourt", "Obio-Akpor", "Bonny"] },
      { nome: "Kano", sigla: "KN", cidades: ["Kano", "Fagge", "Nassarawa"] },
    ],
  },
  {
    nome: "África do Sul",
    codigo: "ZA",
    estados: [
      { nome: "Gauteng", sigla: "GP", cidades: ["Joanesburgo", "Pretória", "Soweto", "Sandton", "Midrand", "Ekurhuleni"] },
      { nome: "Cabo Ocidental", sigla: "WC", cidades: ["Cidade do Cabo", "Stellenbosch", "Paarl", "George", "Knysna"] },
      { nome: "KwaZulu-Natal", sigla: "KZN", cidades: ["Durban", "Pietermaritzburg", "Richards Bay", "Newcastle", "Umhlanga"] },
    ],
  },
  {
    nome: "Paraguai",
    codigo: "PY",
    estados: [
      { nome: "Distrito Capital", sigla: "ASU", cidades: ["Assunção"] },
      { nome: "Central", sigla: "CEN", cidades: ["San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Ñemby"] },
      { nome: "Alto Paraná", sigla: "APA", cidades: ["Ciudad del Este", "Hernandarias", "Minga Guazú", "Presidente Franco"] },
      { nome: "Itapúa", sigla: "ITA", cidades: ["Encarnación", "Hohenau", "Obligado"] },
    ],
  },
  {
    nome: "Uruguai",
    codigo: "UY",
    estados: [
      { nome: "Montevidéu", sigla: "MO", cidades: ["Montevidéu"] },
      { nome: "Canelones", sigla: "CA", cidades: ["Las Piedras", "Ciudad de la Costa", "Pando", "La Paz", "Canelones"] },
      { nome: "Salto", sigla: "SA", cidades: ["Salto"] },
      { nome: "Maldonado", sigla: "MA", cidades: ["Maldonado", "Punta del Este", "San Carlos"] },
    ],
  },
  {
    nome: "Chile",
    codigo: "CL",
    estados: [
      { nome: "Santiago", sigla: "RM", cidades: ["Santiago", "Puente Alto", "Maipú", "La Florida", "Las Condes", "San Bernardo", "Peñalolén", "Ñuñoa", "Providencia", "Vitacura"] },
      { nome: "Valparaíso", sigla: "VS", cidades: ["Valparaíso", "Viña del Mar", "Quilpué", "Villa Alemana"] },
      { nome: "Biobío", sigla: "BI", cidades: ["Concepción", "Talcahuano", "Chillán", "Los Ángeles"] },
      { nome: "Araucanía", sigla: "AR", cidades: ["Temuco", "Padre las Casas", "Villarrica", "Pucón"] },
    ],
  },
  {
    nome: "Peru",
    codigo: "PE",
    estados: [
      { nome: "Lima", sigla: "LIM", cidades: ["Lima", "Callao", "San Juan de Lurigancho", "San Martín de Porres", "Ate", "Comas", "Villa El Salvador"] },
      { nome: "Arequipa", sigla: "AQP", cidades: ["Arequipa", "Camaná", "Mollendo"] },
      { nome: "Cusco", sigla: "CUS", cidades: ["Cusco", "Sicuani", "Quillabamba"] },
      { nome: "La Libertad", sigla: "LAL", cidades: ["Trujillo", "Chepén", "Pacasmayo"] },
    ],
  },
  {
    nome: "Suíça",
    codigo: "CH",
    estados: [
      { nome: "Zurique", sigla: "ZH", cidades: ["Zurique", "Winterthur", "Uster", "Dübendorf"] },
      { nome: "Berna", sigla: "BE", cidades: ["Berna", "Biel/Bienne", "Thun", "Interlaken"] },
      { nome: "Genebra", sigla: "GE", cidades: ["Genebra", "Vernier", "Lancy", "Meyrin"] },
      { nome: "Vaud", sigla: "VD", cidades: ["Lausanne", "Montreux", "Nyon", "Yverdon-les-Bains"] },
      { nome: "Ticino", sigla: "TI", cidades: ["Lugano", "Bellinzona", "Locarno", "Mendrisio"] },
    ],
  },
];
